// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIE6kcwpvugT_uTrWVDmLTde1CmAZsYuE',
    appId: '1:687104273888:web:04a8eb8916527f1fee4f85',
    messagingSenderId: '687104273888',
    projectId: 'fir-checkapp-be193',
    authDomain: 'fir-checkapp-be193.firebaseapp.com',
    storageBucket: 'fir-checkapp-be193.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDMBZ8AnOg6RjvNkbybuV9OHvShJmk42M',
    appId: '1:687104273888:android:f0abd164ef8e2574ee4f85',
    messagingSenderId: '687104273888',
    projectId: 'fir-checkapp-be193',
    storageBucket: 'fir-checkapp-be193.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYTeWclfggsbqv8exubb8AiqYn2QffExc',
    appId: '1:687104273888:ios:b27435f107947f25ee4f85',
    messagingSenderId: '687104273888',
    projectId: 'fir-checkapp-be193',
    storageBucket: 'fir-checkapp-be193.appspot.com',
    iosBundleId: 'com.example.practiceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYTeWclfggsbqv8exubb8AiqYn2QffExc',
    appId: '1:687104273888:ios:d5eeb01de887a8b2ee4f85',
    messagingSenderId: '687104273888',
    projectId: 'fir-checkapp-be193',
    storageBucket: 'fir-checkapp-be193.appspot.com',
    iosBundleId: 'com.example.practiceFirebase.RunnerTests',
  );
}
