// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRn62atPS8ERoKDvcFsxa0VSipe1jxojc',
    appId: '1:449624093990:web:1455a60b39f64ef5f1bde7',
    messagingSenderId: '449624093990',
    projectId: 'fir-data-eef54',
    authDomain: 'fir-data-eef54.firebaseapp.com',
    storageBucket: 'fir-data-eef54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA944VOUb53P3DhAex8EwNNA7bM1dQlLTo',
    appId: '1:449624093990:android:79d02842c785af33f1bde7',
    messagingSenderId: '449624093990',
    projectId: 'fir-data-eef54',
    storageBucket: 'fir-data-eef54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzFXWQ7MPrAyA6-BgYjno5m_mhVepNURM',
    appId: '1:449624093990:ios:cc9174068fc74558f1bde7',
    messagingSenderId: '449624093990',
    projectId: 'fir-data-eef54',
    storageBucket: 'fir-data-eef54.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
